''' displays for tensor based data:  images, voxels, vector fields, ... '''

# NOTE: all these were previously in madcad.displays

class ImageDisplay:  ...
class VoxelDisplay:  ...
class FieldDisplay:  ...
