''' displays for visual markers: points, arrows, texts, ... '''

# NOTE: all these were previously in madcad.displays

class PointDisplay:  ...
class TextDisplay: ...
class AxisDisplay: ...
class BoxDisplay: ...
