''' displays for mesh data:  cloud points, webs, meshes, ... '''

# NOTE: all these were previously in madcad.displays

class MeshDisplay:   ...
class WebDisplay:  ...

class Vertices:   ...
class SurfaceDisplay:  ...
class GhostDisplay:  ...
class EdgesDisplay:  ...
