''' displays for annotations: labels, markups, cotations, ... '''

# NOTE this is the part of the previous madcad.scheme that is 3d-only or open-GL only
# NOTE the annotations functions are staying in madcad.scheme because they do not support only openGL

class Scheme: ...
class SchemeDisplay:  ...

def world():	...
def screen():   ...
def halo_world(position):   ...
...
